import * as types from './types';


export const addGaild = (text) => ({ type: types.ADD_GAILD, text })
export const cunGaiid = (text) => ({ type: types.CUN_GAI_ID, text })
export const getGaiid = (text) => ({ type: types.GET_GAI_ID, text })
export const xiuGaiid = (text) => ({ type: types.XIU_GAI_ID, text })
export const getZhaobiao = (text) => ({ type: types.GET_ZHAOBIAO, text })
export const postZhaobiao = (text) => ({ type: types.POST_ZHAOBIAO, text })
export const loginStatuFail = (text) => ({ type: types.LOGIN_STATU_FAIL, text })
export const loginStatu = (text) => ({ type: types.LOGIN_STATU, text })
export const logIn = (text) => ({ type: types.LOG_IN, text })
export const getCity = (text) => ({ type: types.GET_CITY, text })
export const postMember = (text) => ({ type: types.POST_MEMBER, text })
export const getMember = (text) => ({ type: types.GET_MEMBER, text })
export const xiuGaicom = (text) => ({ type: types.XIU_GAI_COM, text })
export const getGaicom = (text) => ({ type: types.GET_GAI_COM, text })
export const cunGaicom = (text) => ({ type: types.CUN_GAI_COM, text })
export const addCom = (text) => ({ type: types.ADD_COM, text })
export const firstCity = (text) => ({ type: types.FIRST_CITY, text })
export const adminGaicom = (text) => ({ type: types.ADMIN_GAI_COM, text })
export const tiShi = (text) => ({ type: types.TI_SHI, text })
export const xiuGaipassword = (text) => ({ type: types.XIU_GAI_PASSWORD, text })
export const getZizhi = (text) => ({ type: types.GET_ZIZHI, text })
export const setZizhi = (text) => ({ type: types.SET_ZIZHI, text })
export const addZizhi = (text) => ({ type: types.ADD_ZIZHI, text })
export const delZizhi = (text) => ({ type: types.DEL_ZIZHI, text })
export const getDesign = (text) => ({ type: types.GET_DESIGN, text })
export const reduxGetdesign = (text) => ({ type: types.REDUX_GET_DESIGN, text })
export const delDesign = (text) => ({ type: types.DEL_DESIGN, text })
export const cunDesign = (text) => ({ type: types.CUN_DESIGN, text })
export const getGongdiMessage = (text) => ({ type: types.GET_GONGDI_MESSAGE, text })
export const reduxGongdiMessage = (text) => ({ type: types.REDUX_GONGDI_MESSAGE, text })
export const getGongdiList  = (text) =>({type:types.GET_GONGDI_LIST, text })
export const reduxGongdiList= (text) =>({type:types.REDUX_GONGDI_LIST ,text})
export const gaiGongdiMessage=(text) =>({type:types.GAI_GONGDI_MESSAGE,text})
export const getJinDuImg = (text) => ({ type: types.GET_JINDU_IMG, text })
export const reduxJinDuImg = (text) => ({ type: types.REDUX_JINDU_IMG, text })
export const cunJinDuImg   =(text)  => ({ type:types.CUN_JINDU_IMG,text})
export const delJinDuImg = (text) => ({ type: types.DEL_JINDU_IMG,text})
export const newJinDuImg = (text) =>({type:types.NEW_JINDU_IMG,text})
export const delJinDu = (text) =>   ({type:types.DEL_JINDU,text})
export const getCompanyZixunList=(text)=>({type:types.GET_COMPANY_ZIXUN_LIST,text})
export const reduxCompanyZixunList = (text) => ({ type: types.REDUX_COMPANY_ZIXUN_LIST, text })
export const getCompanyZixunAbout=(text)=>({type:types.GET_COMPANY_ZIXUN_ABOUT,text})
export const reduxCompanyZixunAbout = (text) => ({ type: types.REDUX_COMPANY_ZIXUN_ABOUT, text })
export const gaiCompanyZixunAbout=(text)=>({type:types.GAI_COMPANY_ZIXUN_ABOUT,text})
export const delCompanyZixunList = (text) => ({ type: types.DEL_COMPANY_ZIXUN_LIST,text})
export const addCompanyZixun = (text) => ({ type: types.ADD_COMPANY_ZIXUN,text})