export const GET_CITY ='GET_CITY';                 //城市   
export const LOG_IN = 'LOG_IN'                     //登陆
export const LOGIN_STATU ='LOGIN_STATU'            //登录验证状态成功
export const LOGIN_STATU_FAIL ='LOGIN_STATU_FAIL'  //登录验证状态失败
export const POST_ZHAOBIAO ='POST_ZHAOBIAO'        //发起获取招标
export const GET_ZHAOBIAO ='GET_ZHAOBIAO'          //获取招标列表
export const XIU_GAI_ID = 'XIU_GAI_ID'             //发出修改标内容id
export const GET_GAI_ID = 'GET_GAI_ID'             //saga拿到标内容id
export const CUN_GAI_ID = 'CUN_GAI_ID'             //saga拿到标内容id
export const ADD_GAILD = 'ADD_GAILD'               //存新建
export const POST_MEMBER = 'POST_MEMBER'           //发出获取公司列表
export const GET_MEMBER = 'GET_MEMBER'             //获取公司列表
export const XIU_GAI_COM = 'XIU_GAI_COM'           //发出修改标内容id
export const GET_GAI_COM = 'GET_GAI_COM'           //saga拿到标内容id
export const CUN_GAI_COM = 'CUN_GAI_COM'           //saga拿到标内容id
export const ADD_COM = 'ADD_COM'                   //存新建
export const FIRST_CITY = 'FIRST_CITY'             //设置默认城市
export const ADMIN_GAI_COM ="ADMIN_GAI_COM"        //商家自定义管理信息发起保存
export const TI_SHI = 'TI_SHI'                     //操作提示
export const XIU_GAI_PASSWORD ='XIU_GAI_PASSWORD'  //修改装修公司登录密码
export const GET_ZIZHI = 'GET_ZIZHI'               //获取资质
export const SET_ZIZHI = 'SET_ZIZHI'               //设置redux资质图片列表
export const ADD_ZIZHI ='ADD_ZIZHI'                //发出上传请求
export const DEL_ZIZHI = 'DEL_ZIZHI'               //发出删除请求
export const GET_DESIGN = 'GET_DESIGN'             //发出获取设计师列表请求
export const REDUX_GET_DESIGN ='REDUX_GET_DESIGN'  //将获取到的设计师存入redux
export const DEL_DESIGN = 'DEL_DESIGN'             //发出删除设计师请求
export const CUN_DESIGN = 'CUN_DESIGN'             //发出添加上传图片请求
export const GET_GONGDI_LIST='GET_GONGDI_LIST'     //发出获取工地列表请求
export const REDUX_GONGDI_LIST ='REDUX_GONGDI_LIST'//将工地列表存入redux
export const GET_GONGDI_MESSAGE ='GET_GONGDI_MESSAGE' //发出获取工地信息请求
export const REDUX_GONGDI_MESSAGE ='REDUX_GONGDI_MESSAGE' //将获取到的信息存入redux
export const GAI_GONGDI_MESSAGE ='GAI_GONGDI_MESSAGE'//发出修改保存工地信息请求
export const GET_JINDU_IMG ='GET_JINDU_IMG'         //发出获取施工阶段图片请求
export const REDUX_JINDU_IMG ='REDUX_JINDU_IMG'     //将施工阶段图片存入redux
export const CUN_JINDU_IMG = 'CUN_JINDU_IMG'        //发出存储施工阶段图片请求
export const DEL_JINDU_IMG = 'DEL_JINDU_IMG'        //发出删除施工阶段图片请求
export const NEW_JINDU_IMG ='NEW_JINDU_IMG'         //发出存储新建施工阶段请求
export const DEL_JINDU = 'DEL_JINDU'                //发出删除施工请求
export const GET_COMPANY_ZIXUN_LIST ='GET_COMPANY_ZIXUN_LIST' //发出获取公司咨询请求
export const REDUX_COMPANY_ZIXUN_LIST = 'REDUX_COMPANY_ZIXUN_LIST' //将公司咨询存入redux

 